PROMPT PROCESSING FOR SMTM_QUEUE_MENU_001

BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'ACQUIRED',
'قياسي',
'مكتسب',
'المهام المكتسبة'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'AGING',
'اتفاقية مستوى الخدمة',
'التقادم',
'مهام التقادم'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'ASSIGNED',
'قياسي',
'معين',
'المهام الموكلة'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'COMPLETED',
'قياسي',
'مكتمل',
'مهام مكتملة'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'ESCALATED',
'المشرف',
'تم التصعيد',
'المهام التي تم تصعيدها'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'ESCALATED_STD',
'قياسي',
'تم التصعيد',
'المهام التي تم تصعيدها'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'EXPIRED',
'اتفاقية مستوى الخدمة',
'منتهي الصلاحية',
'المهام منتهية الصلاحية'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'HIGH',
'الأولوية',
'مرتفع',
'المهام ذات الأولوية الأعلى'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'LOW',
'الأولوية',
'منخفض',
'المهام ذات الأولوية الأدنى'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'MEDIUM',
'الأولوية',
'متوسط ',
'أولوية متوسطة'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'PENDING',
'قياسي',
'معلق',
'مهام قيد الانتظار'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'RM_APP_STAT',
'مهام قائمة انتظار مدير العلاقات',
'تتبع حالة الطلب',
'تتبع حالة الطلب'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'RM_DOCMISSING',
'مهام قائمة انتظار مدير العلاقات',
'طلبات المستندات المفقودة',
'طلبات المستندات المفقودة'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'RM_MONETARY_ASPECT',
'مهام قائمة انتظار مدير العلاقات',
'لوحة معلومات مدير العلاقات في الجانب النقدي',
'لوحة معلومات مدير العلاقات في الجانب النقدي'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'RM_PEND_ACCEPT',
'مهام قائمة انتظار مدير العلاقات',
'الطلبات المعلقة بانتظار الموافقة',
'الطلبات المعلقة بانتظار الموافقة'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'RO_ESCALATED',
'مهام قائمة انتظار المكتب الإقليمي',
'الطلبات التي تم تصعيدها',
'الطلبات التي تم تصعيدها'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'RO_EXT_AGNCY',
'مهام قائمة انتظار المكتب الإقليمي',
'الطلبات من الوكالات الخارجية',
'الطلبات من الوكالات الخارجية'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'RO_POTENTIAL',
'مهام قائمة انتظار المكتب الإقليمي',
'الطلبات المحتملة للاعتماد',
'الطلبات المحتملة للاعتماد'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'RO_PRODUCTIVITY',
'مهام قائمة انتظار المكتب الإقليمي',
'لوحة معلومات الإنتاجية',
'لوحة معلومات الإنتاجية'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'RO_STATUS_TRACK',
'مهام قائمة انتظار المكتب الإقليمي',
'تتبع حالة الطلب',
'تتبع حالة الطلب'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'RO_TO_APPROVE',
'مهام قائمة انتظار المكتب الإقليمي',
'الطلبات المطلوب اعتمادها',
'الطلبات المطلوب اعتمادها'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'SUPERVISOR',
'قياسي',
'المشرف',
'مهام المشرف'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ARB',
'TODAY',
'قياسي',
'اليوم',
'مهام اليوم الخاصة بي'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'ACQUIRED',
'标准',
'获取',
'已获得的任务'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'AGING',
'SLA',
'时限',
'确定任务时限'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'ASSIGNED',
'标准',
'已分配',
'指派任务'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'COMPLETED',
'标准',
'已完成',
'已完成任务'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'ESCALATED',
'监管人',
'已升级',
'已升级任务'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'ESCALATED_STD',
'标准',
'已升级',
'已升级任务'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'EXPIRED',
'SLA',
'已过期',
'已过期任务'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'HIGH',
'优先级',
'高',
'高优先级任务'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'LOW',
'优先级',
'低',
'低优先级任务'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'MEDIUM',
'优先级',
'中 ',
'中优先级'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'PENDING',
'标准',
'等待',
'任务暂停'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'RM_APP_STAT',
'客户经理队列任务',
'申请状态跟踪',
'申请状态跟踪'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'RM_DOCMISSING',
'客户经理队列任务',
'缺少单据的申请',
'缺少单据的申请'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'RM_MONETARY_ASPECT',
'客户经理队列任务',
'货币方面的关系经理控制面板',
'货币方面的关系经理控制面板'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'RM_PEND_ACCEPT',
'客户经理队列任务',
'申请等待接受',
'申请等待接受'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'RO_ESCALATED',
'RO 队列任务',
'升级的申请',
'升级的申请'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'RO_EXT_AGNCY',
'RO 队列任务',
'外部机构的申请',
'外部机构的申请'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'RO_POTENTIAL',
'RO 队列任务',
'潜在的审批申请',
'潜在的审批申请'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'RO_PRODUCTIVITY',
'RO 队列任务',
'生产率控制面板',
'生产率控制面板'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'RO_STATUS_TRACK',
'RO 队列任务',
'申请状态跟踪',
'申请状态跟踪'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'RO_TO_APPROVE',
'RO 队列任务',
'要批准的申请',
'要批准的申请'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'SUPERVISOR',
'标准',
'监管人',
'监管人任务'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('CHS',
'TODAY',
'标准',
'今日',
'我今天的任务'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'ACQUIRED',
'Standard',
'Acquired',
'Acquired Tasks'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'AGING',
'SLA',
'Aging',
'Aging Tasks'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'ASSIGNED',
'Standard',
'Assigned',
'Assigned Tasks'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'COMPLETED',
'Standard',
'Completed',
'Completed Tasks'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'ESCALATED',
'Supervisor',
'Escalated',
'Escalated Tasks'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'ESCALATED_STD',
'Standard',
'Escalated',
'Escalated Tasks'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'EXPIRED',
'SLA',
'Expired',
'Expired Tasks'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'HIGH',
'Priority',
'High',
'High Priority Tasks'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'LOW',
'Priority',
'Low',
'Low Priority Tasks'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'MEDIUM',
'Priority',
'Medium ',
'Medium Priority'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'PENDING',
'Standard',
'Pending',
'Tasks on Hold'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'RM_APP_STAT',
'RM Queue Tasks',
'Application Status Tracking',
'Application Status Tracking'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'RM_DOCMISSING',
'RM Queue Tasks',
'Document Missing Applications',
'Document Missing Applications'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'RM_MONETARY_ASPECT',
'RM Queue Tasks',
'Relation Manager Dashboard on Monetary aspect',
'Relation Manager Dashboard on Monetary aspect'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'RM_PEND_ACCEPT',
'RM Queue Tasks',
'Applications Pend Acceptance',
'Applications Pend Acceptance'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'RO_ESCALATED',
'RO Queue Tasks',
'Escalated Applications',
'Escalated Applications'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'RO_EXT_AGNCY',
'RO Queue Tasks',
'Applications from External Agencies',
'Applications from External Agencies'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'RO_POTENTIAL',
'RO Queue Tasks',
'Potential Applications for Approval',
'Potential Applications for Approval'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'RO_PRODUCTIVITY',
'RO Queue Tasks',
'Productivity Dashboard',
'Productivity Dashboard'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'RO_STATUS_TRACK',
'RO Queue Tasks',
'Application Status Tracking',
'Application Status Tracking'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'RO_TO_APPROVE',
'RO Queue Tasks',
'Applications to be approved',
'Applications to be approved'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'SUPERVISOR',
'Standard',
'Supervisor',
'Supervisor Tasks'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ENG',
'TODAY',
'Standard',
'Today',
'My tasks for today'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'ACQUIRED',
'Estándar',
'Adquirido',
'Tareas adquiridas'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'AGING',
'SLA',
'Antigüedad',
'Tareas de antigüedad'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'ASSIGNED',
'Estándar',
'Asignado',
'Tareas asignadas'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'COMPLETED',
'Estándar',
'Finalizado',
'Tareas completadas'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'ESCALATED',
'Supervisor',
'Aumentado',
'Tareas escaladas'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'ESCALATED_STD',
'Estándar',
'Aumentado',
'Tareas escaladas'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'EXPIRED',
'SLA',
'Caducado',
'Tareas caducadas'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'HIGH',
'Prioridad',
'Alta',
'Tareas de prioridad alta'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'LOW',
'Prioridad',
'Bajo',
'Tareas de prioridad baja'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'MEDIUM',
'Prioridad',
'Medio ',
'Prioridad media'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'PENDING',
'Estándar',
'Pendiente',
'Tareas retenidas'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'RM_APP_STAT',
'Tareas de cola de gestor de relaciones',
'Seguimiento de estado de solicitud',
'Seguimiento de estado de solicitud'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'RM_DOCMISSING',
'Tareas de cola de gestor de relaciones',
'Solicitudes con falta de documentos',
'Solicitudes con falta de documentos'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'RM_MONETARY_ASPECT',
'Tareas de cola de gestor de relaciones',
'Panel de control de gestor de relaciones en aspecto monetario',
'Panel de control de gestor de relaciones en aspecto monetario'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'RM_PEND_ACCEPT',
'Tareas de cola de gestor de relaciones',
'Solicitudes pendientes de aceptación',
'Solicitudes pendientes de aceptación'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'RO_ESCALATED',
'Tareas de cola de oficina regional',
'Solicitudes escaladas',
'Solicitudes escaladas'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'RO_EXT_AGNCY',
'Tareas de cola de oficina regional',
'Solicitudes de agencias externas',
'Solicitudes de agencias externas'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'RO_POTENTIAL',
'Tareas de cola de oficina regional',
'Solicitudes potenciales para aprobación',
'Solicitudes potenciales para aprobación'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'RO_PRODUCTIVITY',
'Tareas de cola de oficina regional',
'Panel de control de productividad',
'Panel de control de productividad'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'RO_STATUS_TRACK',
'Tareas de cola de oficina regional',
'Seguimiento de estado de solicitud',
'Seguimiento de estado de solicitud'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'RO_TO_APPROVE',
'Tareas de cola de oficina regional',
'Solicitudes por aprobar',
'Solicitudes por aprobar'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'SUPERVISOR',
'Estándar',
'Supervisor',
'Tareas de supervisor'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('ESP',
'TODAY',
'Estándar',
'Actual',
'Mis tareas para hoy'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'ACQUIRED',
'Standard',
'Acquis',
'Tâches acquises'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'AGING',
'Contrat niveau service',
'Ancienneté',
'Tâches d''ancienneté'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'ASSIGNED',
'Standard',
'Affecté',
'Tâches affectées'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'COMPLETED',
'Standard',
'Terminé',
'Tâches exécutées'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'ESCALATED',
'Superviseur',
'Escalade',
'Tâches escaladées'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'ESCALATED_STD',
'Standard',
'Escalade',
'Tâches escaladées'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'EXPIRED',
'Contrat niveau service',
'Expiré',
'Tâches expirées'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'HIGH',
'Priorité',
'Elevée',
'Tâches priorité haute'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'LOW',
'Priorité',
'Faible',
'Tâches priorité basse'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'MEDIUM',
'Priorité',
'Moyenne ',
'Priorité moyenne'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'PENDING',
'Standard',
'En attente',
'Tâches en attente'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'RM_APP_STAT',
'Tâches file d''attente RM',
'Suivi statut demande',
'Suivi statut demande'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'RM_DOCMISSING',
'Tâches file d''attente RM',
'Demandes avec documents manquants',
'Demandes avec documents manquants'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'RM_MONETARY_ASPECT',
'Tâches file d''attente RM',
'Tableau de bord RM sur aspect monétaire',
'Tableau de bord RM sur aspect monétaire'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'RM_PEND_ACCEPT',
'Tâches file d''attente RM',
'Demandes en attente d''acceptation',
'Demandes en attente d''acceptation'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'RO_ESCALATED',
'Tâches file d''attente CR',
'Demandes escaladées',
'Demandes escaladées'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'RO_EXT_AGNCY',
'Tâches file d''attente CR',
'Demandes d''agences externes',
'Demandes d''agences externes'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'RO_POTENTIAL',
'Tâches file d''attente CR',
'Demandes potentielles pour approbation',
'Demandes potentielles pour approbation'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'RO_PRODUCTIVITY',
'Tâches file d''attente CR',
'Tableau de bord productivité',
'Tableau de bord productivité'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'RO_STATUS_TRACK',
'Tâches file d''attente CR',
'Suivi statut demande',
'Suivi statut demande'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'RO_TO_APPROVE',
'Tâches file d''attente CR',
'Demandes à approuver',
'Demandes à approuver'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'SUPERVISOR',
'Standard',
'Superviseur',
'Tâches superviseur'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('FRC',
'TODAY',
'Standard',
'Aujourd''hui',
'Mes tâches pour aujourd''hui'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('GER',
'ACQUIRED',
'Standard',
'Erworben',
'Angenommene Aufgaben'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('GER',
'ASSIGNED',
'Standard',
'Zugewiesen',
'Zugewiesene Aufgaben'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('GER',
'COMPLETED',
'Standard',
'Abgeschlossen',
'Abgeschlossene Aufgaben'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('GER',
'PENDING',
'Standard',
'Anhängig',
'Aufgaben in Wartestellung'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('GER',
'SUPERVISOR',
'Standard',
'Vorgesetzter',
'Aufgaben für Vorgesetzte'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('JPN',
'ACQUIRED',
'標準',
'取得済',
'取得タスク'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('JPN',
'ASSIGNED',
'標準',
'割当済',
'割当済タスク'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('JPN',
'COMPLETED',
'標準',
'完了',
'完了タスク'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('JPN',
'PENDING',
'標準',
'保留中',
'保留中タスク'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('JPN',
'SUPERVISOR',
'標準',
'監督者',
'監督タスク'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('POR',
'ESCALATED_STD',
'Standard',
'Escalonada',
'Tarefas Escalonadas'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('POR',
'MEDIUM',
'Prioridade',
'Média ',
'Prioridade Média'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('POR',
'RM_APP_STAT',
'Tarefas da Fila de Espera do GR',
'Controlo do Estado da Proposta',
'Controlo do Estado da Proposta'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('POR',
'RM_DOCMISSING',
'Tarefas da Fila de Espera do GR',
'Documento:Propostas em Falta',
'Documento:Propostas em Falta'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('POR',
'RM_MONETARY_ASPECT',
'Tarefas da Fila de Espera do GR',
'Painel do Gestor de Relações no aspeto Monetário',
'Painel do Gestor de Relações no aspeto Monetário'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('POR',
'RM_PEND_ACCEPT',
'Tarefas da Fila de Espera do GR',
'Aceitação de Propostas Pendentes',
'Aceitação de Propostas Pendentes'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('POR',
'RO_ESCALATED',
'Tarefas da Fila de Espera do RR',
'Propostas Escalonadas',
'Propostas Escalonadas'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('POR',
'RO_EXT_AGNCY',
'Tarefas da Fila de Espera do RR',
'Propostas das Agências Externas',
'Propostas das Agências Externas'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('POR',
'RO_POTENTIAL',
'Tarefas da Fila de Espera do RR',
'Propostas Potenciais para Aprovação',
'Propostas Potenciais para Aprovação'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('POR',
'RO_PRODUCTIVITY',
'Tarefas da Fila de Espera do RR',
'Painel de Produtividade',
'Painel de Produtividade'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('POR',
'RO_STATUS_TRACK',
'Tarefas da Fila de Espera do RR',
'Controlo do Estado da Proposta',
'Controlo do Estado da Proposta'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('POR',
'RO_TO_APPROVE',
'Tarefas da Fila de Espera do RR',
'Propostas a aprovar',
'Propostas a aprovar'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'ACQUIRED',
'Tiêu chuẩn',
'Đã tiếp nhận',
'Công việc đã tiếp nhận'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'AGING',
'Kế toán sổ chi tiết',
'Tuổi nợ',
'Công việc theo dõi tuổi giao dịch'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'ASSIGNED',
'Tiêu chuẩn',
'Đã gán',
'Công việc đã gán'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'COMPLETED',
'Tiêu chuẩn',
'Đã hoàn thành',
'Công việc đã hoàn thành'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'ESCALATED',
'Người giám sát',
'Thông báo cho cấp trên',
'Công việc đã báo cáo lên cấp trên'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'ESCALATED_STD',
'Tiêu chuẩn',
'Thông báo cho cấp trên',
'Công việc đã báo cáo lên cấp trên'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'EXPIRED',
'Kế toán sổ chi tiết',
'Đã hết hạn',
'Công việc đã hết hạn'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'HIGH',
'Ưu tiên',
'Cao',
'Công việc có mức độ ưu tiên cao'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'LOW',
'Ưu tiên',
'Thấp',
'Công việc có mức độ ưu tiên thấp'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'MEDIUM',
'Ưu tiên',
'Trung bình',
'Ưu tiên trung bình'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'PENDING',
'Tiêu chuẩn',
'Đang treo',
'Công việc đang treo'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'RM_APP_STAT',
'Nhiệm vụ trong hàng đợi của quản lý quan hệ',
'Theo dõi trạng thái đơn yêu cầu',
'Theo dõi trạng thái đơn yêu cầu'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'RM_DOCMISSING',
'Nhiệm vụ trong hàng đợi của quản lý quan hệ',
'Đơn yêu cầu thiếu chứng từ',
'Đơn yêu cầu thiếu chứng từ'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'RM_MONETARY_ASPECT',
'Nhiệm vụ trong hàng đợi của quản lý quan hệ',
'Dashboard của quản lý quan hệ về khía cạnh tiền tệ',
'Dashboard của quản lý quan hệ về khía cạnh tiền tệ'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'RM_PEND_ACCEPT',
'Nhiệm vụ trong hàng đợi của quản lý quan hệ',
'Đơn yêu cầu đang chờ chấp nhận',
'Đơn yêu cầu đang chờ chấp nhận'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'RO_ESCALATED',
'Nhiệm vụ trong hàng đợi của chuyên viên quan hệ',
'Đơn yêu cầu đã thông báo cho cấp trên',
'Đơn yêu cầu đã thông báo cho cấp trên'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'RO_EXT_AGNCY',
'Nhiệm vụ trong hàng đợi của chuyên viên quan hệ',
'Đơn yêu cầu từ cơ quan bên ngoài',
'Đơn yêu cầu từ cơ quan bên ngoài'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'RO_POTENTIAL',
'Nhiệm vụ trong hàng đợi của chuyên viên quan hệ',
'Đơn yêu cầu có thể được phê duyệt',
'Đơn yêu cầu có thể được phê duyệt'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'RO_PRODUCTIVITY',
'Nhiệm vụ trong hàng đợi của chuyên viên quan hệ',
'Dashboard năng suất',
'Dashboard năng suất'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'RO_STATUS_TRACK',
'Nhiệm vụ trong hàng đợi của chuyên viên quan hệ',
'Theo dõi trạng thái đơn yêu cầu',
'Theo dõi trạng thái đơn yêu cầu'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'RO_TO_APPROVE',
'Nhiệm vụ trong hàng đợi của chuyên viên quan hệ',
'Đơn yêu cầu sẽ được phê duyệt',
'Đơn yêu cầu sẽ được phê duyệt'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'SUPERVISOR',
'Tiêu chuẩn',
'Người giám sát',
'Công việc của người giám sát'
)
;
END;
/
BEGIN
INSERT INTO SMTM_QUEUE_MENU
(LANG_CODE,QUEUE_ID,MAIN_MENU,SUB_MENU
,DESCRIPTION)
 VALUES 
('VIE',
'TODAY',
'Tiêu chuẩn',
'Hôm nay',
'Công việc của tôi ngày hôm nay'
)
;
END;
/



commit;
